<!DOCTYPE html>
<html lang="es">
<head>
<?php include (VIEWS.'modulos/head.phtml') ?>
<title>Pagina Principal</title>
</head>
<body>
<section>
<div class="logo col-md-12">
	<div class="col-md-4">
		<a href="<?=HOME?>"><img class="img-logo" src="<?=IMAGE?>logo.png" alt=""> </a>
	</div>
	<div class="data-logo col-md-8">
		<p class="txt-logo1">info@dominio.org.pe</p>
		<div class="icons">
			<span class="icon icon-fb"><i class="fa fa-facebook" aria-hidden="true"></i></span>
			<span class="icon icon-tw"><i class="fa fa-twitter" aria-hidden="true"></i></span>
		</div>
		<div class="busqueda">
			<form class="navbar-form navbar-right" role="search">
		        <div class="form-group">
		          <input type="text" class="form-control input-busqueda" placeholder="Busca en el Sitio">
		        </div>
		        <button type="submit" class="btn btn-primary btn-busqueda">Buscar</button>
		    </form>	
		</div>
	</div>

</div>
</section>
<?php include (VIEWS.'modulos/navprincipal.phtml') ?>

<div id="slider_wrap">
    <ul style="display: none;">
		<li lcms_img="<?=IMAGE?>qw.jpg">
		<h4 id="txt_heading">Todos debemos cuidar del agua</h4>
		<br>
            <!-- <p>Desarrollamos tu página web segun tus requerimientos</p>  -->
            <a href="" class="boton">Ver Más</a>           
		</li>
		<li lcms_img="<?=IMAGE?>life.jpg">Unete</li>
		<li lcms_img="<?=IMAGE?>gotas.jpg">Sobre Nosotros</li>
	</ul>
</div>

<div class="container-image-header">
	<div class="row-image-header">
		<div class="cont-img">
			<!-- <img src="<?=IMAGE?>writecode.png" alt=""> -->
		</div>
	</div>
</div>
<section id="body">
	<div class="body-data">
		<div class="body-post col-md-8">
			<div class="noticias">
				<h3>Últimas publicaciones</h3>
				<div class="noticia">
					<div class="panel panel-primary">
					  <div class="panel-heading" style="display: inline-block;width: 100%;">
					    <span class="panel-title" style="width: 60%;display: inline-block;">AGUA DESARROLLO Y BIENESTAR

					    </span>
					    <span style="text-align: left;display: inline-block;"></span>
					  </div>
					  <div class="panel-body">
					    <div class="col-md-5 pbody-image">
					    	<img src="<?=IMAGE?>bienestar.jpg" alt="" style="width: 100%;">
					    </div>
					    <div class="col-md-7 pbody-text">
					    	<ul>
								<li>El agua es un recurso renovable, pero escaso</li>
								<li>En torno al agua, gira el desarrollo sustentable, la salud, el bienestar, paz y seguridad de la población</li>
								<li>El agua es fundamental para la producción de alimentos y desarrollo rural</li>
								<li>Generación de energía eléctrica, dinamiza el sector transporte, industrial y salud</li>
							</ul>
							<!-- <p class="btn btn-primary btn-post">Leer Mas</p> -->
					    </div>					   
					  </div>
					</div>

				<!-- POST -->
				<div class="panel panel-primary">
					<div class="panel-heading" style="display: inline-block;width: 100%;">
					   <span class="panel-title" style="width: 60%;display: inline-block;">EL AGUA EN EL MUNDO </span>
					    <span style="text-align: left;display: inline-block;"></span>
					</div>
					<div class="panel-body">
					    <div class="col-md-5 pbody-image">
					    	<img src="<?=IMAGE?>agua-mundo.jpg" alt="" style="width: 100%;">
					    </div>
					    <div class="col-md-7">
					    	<ul>
								<li>1,200 millones de habitantes no tienen acceso al agua potable</li>
								<li>10 millones de niños mueren antes de los 5 años 
									<p>70% de los pobres son mujeres</p>
									<p>75% de los más pobres son campesinos</p>
								</li>
								<li> Uno de cada cuatro personas no disponen de un sistema de saneamiento adecuado </li>
								<li> Uno de cada cuatro personas en el mundo no tienen acceso al agua dulce </li>
								<li> Las enfermedades transmitidas por el agua son la causa fundamental de la mortalidad infantil </li>
								<li>Por contaminación biológica del agua, cada hora mueren 400 niños menores de 5 años en los países en desarrollo</li>
							</ul>
							<!-- <p class="btn btn-primary btn-post">Leer Mas</p> -->
					    </div>					   
					</div>
				</div>
				<!-- /POST -->

				<!-- POST -->
				<div class="panel panel-primary">
					  <div class="panel-heading" style="display: inline-block;width: 100%;">
					    <span class="panel-title" style="width: 60%;display: inline-block;">CONFLICTOS CON EL AGUA

					    </span>
					    <span style="text-align: left;display: inline-block;"></span>
					  </div>
					  <div class="panel-body">
					    <div class="col-md-5">
					    	<img src="<?=IMAGE?>ca.jpg" alt="" style="width: 100%;">
					    </div>
					    <div class="col-md-7">
					    	<ul>
								<li><span class="negrita">“La próxima guerra mundial será por el agua” </span><br>	
								Vicepresidente del Banco Mundial
								</li>
								<li><span class="negrita">“El agua promete ser en el siglo XXI, lo que el Petróleo fue para el siglo XX. Una preciada mercancía que determinará la riqueza de las Naciones”</span> <br>
								 
								<small>Revista <cite title="Source Title">FORTUNE</cite></small>
								</li>
							</ul>
							<!-- <p class="btn btn-primary btn-post">Leer Mas</p> -->
					    </div>					   
					  </div>
					</div>
				<!-- /POST -->

				<div class="msg">
				<blockquote>
				  <h4 style="color: red;text-align: center;">El acceso a reservas de agua dulce es cuestión de vida o muerte. Por ello, las áreas con reservas importantes serán estratégicas en un futuro cercano.</h4>
				</blockquote>
				</div>
				</div>
			</div>
		</div>
		
	<?php include (VIEWS.'modulos/widget.phtml') ?>
	</div>
	<!-- <div class="clear" style="clear:both;"></div>	 -->
</section>
<div class="clear" style="clear:both;"></div>
<?php include (VIEWS.'modulos/semi-footer.phtml') ?>	
<?php include (VIEWS.'modulos/footer.phtml') ?>	
</body>
</html>