<!DOCTYPE html>
<html lang="es">
<?php include VIEWS.'includes/panel-head.inc'; ?>
<title></title>
</head>
<!-- BODY -->
<body class="nav-md">
<!-- div container -->
<div class="container body">
  <!-- main_container -->  
  <div class="main_container">
    <?php include VIEWS.'includes/panel-menu.inc'; ?>
    <?php include VIEWS.'includes/panel-top-navigation.inc' ?>
    <!-- page content -->
    <div class="right_col" role="main">
      <!-- Header Pages -->
      <div class="header-pages">   
        <div class="col-md-12 col-sm-12 col-xs-12">
          <!-- x panel -->
          <div class="x_panel">
            <div class=" row x_title">
              <div class="col-md-8 col-xs-6">  
              <h2 class="h2-none" style="width:100%;"><span class="glyphicon glyphicon-book"></span> Detalles de las Páginas </h2>
              </div>
              <div class="col-md-4 col-xs-6" style="text-align:right;">
                <a class="well well-sm"> Páginas <span class="badge" style="background-color:rgb(46, 109, 164);color:white;"> 
                <?=count($listapage)?> </span>
                </a>
                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </div>        
            </div>
            <!-- x content-->
            <div class="x_content"> 
            <div class="data-page-panel">
              <div class="" role="tabpanel" data-example-id="togglable-tabs">
                <ul id="tabPages" class="nav nav-tabs bar_tabs" role="tablist">
                  <li role="presentation" class="active">
                  <a class="a-tab" href="#lpages" id="lpages-tab" role="tab" data-toggle="tab" aria-expanded="false">Listado</a></li>
                  <!-- data-toggle="modal" data-target="#FormPage" -->
                  <li role="presentation" class=""><a class="a-tab" href="#formpage" role="tab" id="formpage-tab" data-toggle="tab" aria-expanded="false"> 
                   Agregar </a></li>

                  <li role="presentation" class=""><a class="a-tab" href="#conf" role="tab" id="formpage-tab" data-toggle="tab" aria-expanded="false"> 
                  <i class="fa fa-cog"></i> Otros </a></li>
                </ul>
                <div id="myTabContent" class="tab-content">
                  <div role="tabpanel" class="tab-pane fade active in" id="lpages" aria-labelledby="home-tab">             
                  <div class="row">
                    <div class="col-md-12 table-responsive">
                      <table class="table table-striped table-hover ">
                      <thead>
                        <tr>
                          <th> # (ID) </th>
                          <th> Título de la Página</th>
                          <th> Enlace Permanente <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="Identificardor con la cual se pueda acceder a la sección o enlace"></i></th>
                          <th> Atributo de la Página <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="Característica de la página (sección o enlace)"></i></th>
                          <th> Usuario <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="Usuario que creó o editó la página por última vez"></i></th>
                          <th> Orden de Página</th>
                          <th> Acciones</th>

                        </tr>
                      </thead>
                      <tbody>
                       <?php 
                       foreach ($listadetallesdata['datos'] as $value) { ?>
                        <tr class="success" id="tdata">
                          <td> <?=$value['id_Page']?> </td>
                          <td> <?=$value['title_Page']?>  </td>
                          <td> <?=$value['slug_Page']?>  </td>
                          <td> <?=$value['name_AttributePage']?>  </td>
                          <td> <?=$value['name_User']?>  </td>
                          <td> <?=$value['order_Page']?>  </td>
                          <td id="data<?=$value['slug_Page']?>" data="<?=$value['slug_Page']?>"> <a href="panel/pages/edit/<?=strtolower($value['slug_Page'])?>" class="btn btn-primary"> Editar </a> <a class="eliminar"><button class="btn btn-danger">  Eliminar </button></a>  </td>
                        </tr> 
                       <?php } ?>          
                      </tbody>
                      </table> 
                      <p>
                      	Atributo de la Página:
                      	<li> Sección: Dirección interna hacia una sección de la web, esta se creará según una plantilla</li>
                      	<li> Enlace: Dirección URL externa (ejemplo: un blog externo,etc) Tener en cuenta que esta no se creara si no solo será una hipervínculo hacia otra web</li>
                      </p>
                    </div>
                  </div>   
                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="formpage" aria-labelledby="profile-tab">
                      <div id="progress" style="display:none;" class="progress progress-striped active">
                        <div id="barra-estado" class="progress-bar" style="width: 0%"></div>
                      </div>
                      <div class="col-lg-12 col-xs-12" id="mensaje"></div>
                       <?php include VIEWS.'panel/forms/form-page.inc.php' ?>                   
                  </div> 
                  <div role="tabpanel" class="tab-pane fade" id="conf" aria-labelledby="profile-tab">
                      <div id="progress" style="display:none;" class="progress progress-striped active">
                        <div id="barra-estado" class="progress-bar" style="width: 0%"></div>
                      </div>
                      <div class="col-lg-12 col-xs-12" id="mensajeDP"></div>
                      <div class="row">
                        <div class="col-md-7">
                           <form action="" id="formdata" method="POST" class="form-horizontal form-label-left" novalidate>
                        <!-- ITEM -->
                          <h2>Opciones de la tabla</h2>
                          <div class="item form-group">
                            <label class="control-label col-md-4 col-sm-4 col-xs-12" for="name">AUTO_INCREMENT:
                            </label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                            <input type="number" id="aicr" class="form-control col-md-12 col-xs-12" min="1" max="100"  value="<?=$listadetallesdata['status'][0]['Auto_increment']?>">
                            </div>
                            <div class="col-md-5">

                              <button id="btnincnum" class="btn btn-success"> Aplicar </button><i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="Se definirá el número elegido"></i>

                              <button id="btnincauto" class="btn btn-success"> Automático </button><i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="Se definirá como 1, lo cual sl siguiente en ser insertado tomara el número que falte"></i>
                            </div>

                          </div>
                        <!-- /ITEM -->
                         <div class="ln_solid"></div>
                          <div class="form-group">
                            <div class="col-md-6 col-md-offset-3">
                              <!-- <button type="reset" class="btn btn-primary">Cancel</button> -->
                              
                            </div>
                          </div>
                        </form>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-12 table-responsive">
                          <table class="table table-striped table-hover ">
                          <thead>
                            <tr>
                            
                              <th> Nombre </th>
                              <th> Filas </th>
                              <th> Tamaño </th>
                              <th> Autoincrement </th>
                              <th> Motor </th>
                              <th> Tamaño de Datos </th>
                              <th> Creado el: </th>
                            </tr>
                          </thead>
                          <tbody>
                           <?php 
                           foreach ($listadetallesdata['status'] as $status) { ?>
                            <tr class="success" id="tdata">
                              <td> <?=$status['Name']?> </td>
                              <td> <?=$status['Rows']?>  </td>
                              <td> <?=$status['Data_length']?>  </td>
                              <td> <?=$status['Auto_increment']?>  </td>
                              <td> <?=$status['Engine']?>  </td>
                              <td> <?=$status['Data_length']?> kbs  </td>                          
                              <td> <?=$status['Create_time']?>  </td>
                              <td>  </td>
                            </tr> 
                           <?php } ?>          
                          </tbody>
                          </table> 
                          <p></p>
                        </div>
                      </div>              
                  </div>             
                </div>
              </div>
            </div> 
            </div>
            <!-- x content -->
          </div> 
          <!-- x panel -->
          </div>
        </div>
      </div>
      <!-- /header pages -->
    </div>
    <!-- /page content -->
  </div>
  <!-- main container -->
</div>
<!-- div container -->
<!-- /main_container -->
<?php include VIEWS.'includes/panel-footer-files.inc' ?>
<?php include VIEWS.'includes/panel-footer.inc' ?>
</body>
<!-- /BODY -->
</html>
